/* valadovadelegatemodule.c generated by valac, the Vala compiler
 * generated from valadovadelegatemodule.vala, do not modify */

/* valadovadelegatemodule.vala
 *
 * Copyright (C) 2006-2010  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 *	Raffaele Sandrini <raffaele@sandrini.ch>
 */

#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <valaccode.h>
#include <stdlib.h>
#include <string.h>
#include <valagee.h>


#define VALA_TYPE_DOVA_BASE_MODULE (vala_dova_base_module_get_type ())
#define VALA_DOVA_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_BASE_MODULE, ValaDovaBaseModule))
#define VALA_DOVA_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_BASE_MODULE, ValaDovaBaseModuleClass))
#define VALA_IS_DOVA_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_BASE_MODULE))
#define VALA_IS_DOVA_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_BASE_MODULE))
#define VALA_DOVA_BASE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_BASE_MODULE, ValaDovaBaseModuleClass))

typedef struct _ValaDovaBaseModule ValaDovaBaseModule;
typedef struct _ValaDovaBaseModuleClass ValaDovaBaseModuleClass;
typedef struct _ValaDovaBaseModulePrivate ValaDovaBaseModulePrivate;

#define VALA_TYPE_CCODE_DECLARATION_SPACE (vala_ccode_declaration_space_get_type ())
#define VALA_CCODE_DECLARATION_SPACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_DECLARATION_SPACE, ValaCCodeDeclarationSpace))
#define VALA_CCODE_DECLARATION_SPACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_DECLARATION_SPACE, ValaCCodeDeclarationSpaceClass))
#define VALA_IS_CCODE_DECLARATION_SPACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_DECLARATION_SPACE))
#define VALA_IS_CCODE_DECLARATION_SPACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_DECLARATION_SPACE))
#define VALA_CCODE_DECLARATION_SPACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_DECLARATION_SPACE, ValaCCodeDeclarationSpaceClass))

typedef struct _ValaCCodeDeclarationSpace ValaCCodeDeclarationSpace;
typedef struct _ValaCCodeDeclarationSpaceClass ValaCCodeDeclarationSpaceClass;

#define VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT (vala_dova_base_module_emit_context_get_type ())
#define VALA_DOVA_BASE_MODULE_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaDovaBaseModuleEmitContext))
#define VALA_DOVA_BASE_MODULE_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaDovaBaseModuleEmitContextClass))
#define VALA_DOVA_BASE_MODULE_IS_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_DOVA_BASE_MODULE_IS_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_DOVA_BASE_MODULE_EMIT_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaDovaBaseModuleEmitContextClass))

typedef struct _ValaDovaBaseModuleEmitContext ValaDovaBaseModuleEmitContext;
typedef struct _ValaDovaBaseModuleEmitContextClass ValaDovaBaseModuleEmitContextClass;

#define VALA_TYPE_DOVA_STRUCT_MODULE (vala_dova_struct_module_get_type ())
#define VALA_DOVA_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_STRUCT_MODULE, ValaDovaStructModule))
#define VALA_DOVA_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_STRUCT_MODULE, ValaDovaStructModuleClass))
#define VALA_IS_DOVA_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_STRUCT_MODULE))
#define VALA_IS_DOVA_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_STRUCT_MODULE))
#define VALA_DOVA_STRUCT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_STRUCT_MODULE, ValaDovaStructModuleClass))

typedef struct _ValaDovaStructModule ValaDovaStructModule;
typedef struct _ValaDovaStructModuleClass ValaDovaStructModuleClass;
typedef struct _ValaDovaStructModulePrivate ValaDovaStructModulePrivate;

#define VALA_TYPE_DOVA_METHOD_MODULE (vala_dova_method_module_get_type ())
#define VALA_DOVA_METHOD_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_METHOD_MODULE, ValaDovaMethodModule))
#define VALA_DOVA_METHOD_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_METHOD_MODULE, ValaDovaMethodModuleClass))
#define VALA_IS_DOVA_METHOD_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_METHOD_MODULE))
#define VALA_IS_DOVA_METHOD_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_METHOD_MODULE))
#define VALA_DOVA_METHOD_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_METHOD_MODULE, ValaDovaMethodModuleClass))

typedef struct _ValaDovaMethodModule ValaDovaMethodModule;
typedef struct _ValaDovaMethodModuleClass ValaDovaMethodModuleClass;
typedef struct _ValaDovaMethodModulePrivate ValaDovaMethodModulePrivate;

#define VALA_TYPE_DOVA_CONTROL_FLOW_MODULE (vala_dova_control_flow_module_get_type ())
#define VALA_DOVA_CONTROL_FLOW_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_CONTROL_FLOW_MODULE, ValaDovaControlFlowModule))
#define VALA_DOVA_CONTROL_FLOW_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_CONTROL_FLOW_MODULE, ValaDovaControlFlowModuleClass))
#define VALA_IS_DOVA_CONTROL_FLOW_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_CONTROL_FLOW_MODULE))
#define VALA_IS_DOVA_CONTROL_FLOW_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_CONTROL_FLOW_MODULE))
#define VALA_DOVA_CONTROL_FLOW_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_CONTROL_FLOW_MODULE, ValaDovaControlFlowModuleClass))

typedef struct _ValaDovaControlFlowModule ValaDovaControlFlowModule;
typedef struct _ValaDovaControlFlowModuleClass ValaDovaControlFlowModuleClass;
typedef struct _ValaDovaControlFlowModulePrivate ValaDovaControlFlowModulePrivate;

#define VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE (vala_dova_member_access_module_get_type ())
#define VALA_DOVA_MEMBER_ACCESS_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE, ValaDovaMemberAccessModule))
#define VALA_DOVA_MEMBER_ACCESS_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE, ValaDovaMemberAccessModuleClass))
#define VALA_IS_DOVA_MEMBER_ACCESS_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE))
#define VALA_IS_DOVA_MEMBER_ACCESS_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE))
#define VALA_DOVA_MEMBER_ACCESS_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE, ValaDovaMemberAccessModuleClass))

typedef struct _ValaDovaMemberAccessModule ValaDovaMemberAccessModule;
typedef struct _ValaDovaMemberAccessModuleClass ValaDovaMemberAccessModuleClass;
typedef struct _ValaDovaMemberAccessModulePrivate ValaDovaMemberAccessModulePrivate;

#define VALA_TYPE_DOVA_ASSIGNMENT_MODULE (vala_dova_assignment_module_get_type ())
#define VALA_DOVA_ASSIGNMENT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_ASSIGNMENT_MODULE, ValaDovaAssignmentModule))
#define VALA_DOVA_ASSIGNMENT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_ASSIGNMENT_MODULE, ValaDovaAssignmentModuleClass))
#define VALA_IS_DOVA_ASSIGNMENT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_ASSIGNMENT_MODULE))
#define VALA_IS_DOVA_ASSIGNMENT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_ASSIGNMENT_MODULE))
#define VALA_DOVA_ASSIGNMENT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_ASSIGNMENT_MODULE, ValaDovaAssignmentModuleClass))

typedef struct _ValaDovaAssignmentModule ValaDovaAssignmentModule;
typedef struct _ValaDovaAssignmentModuleClass ValaDovaAssignmentModuleClass;
typedef struct _ValaDovaAssignmentModulePrivate ValaDovaAssignmentModulePrivate;

#define VALA_TYPE_DOVA_METHOD_CALL_MODULE (vala_dova_method_call_module_get_type ())
#define VALA_DOVA_METHOD_CALL_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_METHOD_CALL_MODULE, ValaDovaMethodCallModule))
#define VALA_DOVA_METHOD_CALL_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_METHOD_CALL_MODULE, ValaDovaMethodCallModuleClass))
#define VALA_IS_DOVA_METHOD_CALL_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_METHOD_CALL_MODULE))
#define VALA_IS_DOVA_METHOD_CALL_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_METHOD_CALL_MODULE))
#define VALA_DOVA_METHOD_CALL_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_METHOD_CALL_MODULE, ValaDovaMethodCallModuleClass))

typedef struct _ValaDovaMethodCallModule ValaDovaMethodCallModule;
typedef struct _ValaDovaMethodCallModuleClass ValaDovaMethodCallModuleClass;
typedef struct _ValaDovaMethodCallModulePrivate ValaDovaMethodCallModulePrivate;

#define VALA_TYPE_DOVA_ARRAY_MODULE (vala_dova_array_module_get_type ())
#define VALA_DOVA_ARRAY_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_ARRAY_MODULE, ValaDovaArrayModule))
#define VALA_DOVA_ARRAY_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_ARRAY_MODULE, ValaDovaArrayModuleClass))
#define VALA_IS_DOVA_ARRAY_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_ARRAY_MODULE))
#define VALA_IS_DOVA_ARRAY_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_ARRAY_MODULE))
#define VALA_DOVA_ARRAY_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_ARRAY_MODULE, ValaDovaArrayModuleClass))

typedef struct _ValaDovaArrayModule ValaDovaArrayModule;
typedef struct _ValaDovaArrayModuleClass ValaDovaArrayModuleClass;
typedef struct _ValaDovaArrayModulePrivate ValaDovaArrayModulePrivate;

#define VALA_TYPE_DOVA_OBJECT_MODULE (vala_dova_object_module_get_type ())
#define VALA_DOVA_OBJECT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_OBJECT_MODULE, ValaDovaObjectModule))
#define VALA_DOVA_OBJECT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_OBJECT_MODULE, ValaDovaObjectModuleClass))
#define VALA_IS_DOVA_OBJECT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_OBJECT_MODULE))
#define VALA_IS_DOVA_OBJECT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_OBJECT_MODULE))
#define VALA_DOVA_OBJECT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_OBJECT_MODULE, ValaDovaObjectModuleClass))

typedef struct _ValaDovaObjectModule ValaDovaObjectModule;
typedef struct _ValaDovaObjectModuleClass ValaDovaObjectModuleClass;
typedef struct _ValaDovaObjectModulePrivate ValaDovaObjectModulePrivate;

#define VALA_TYPE_DOVA_VALUE_MODULE (vala_dova_value_module_get_type ())
#define VALA_DOVA_VALUE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_VALUE_MODULE, ValaDovaValueModule))
#define VALA_DOVA_VALUE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_VALUE_MODULE, ValaDovaValueModuleClass))
#define VALA_IS_DOVA_VALUE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_VALUE_MODULE))
#define VALA_IS_DOVA_VALUE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_VALUE_MODULE))
#define VALA_DOVA_VALUE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_VALUE_MODULE, ValaDovaValueModuleClass))

typedef struct _ValaDovaValueModule ValaDovaValueModule;
typedef struct _ValaDovaValueModuleClass ValaDovaValueModuleClass;
typedef struct _ValaDovaValueModulePrivate ValaDovaValueModulePrivate;

#define VALA_TYPE_DOVA_DELEGATE_MODULE (vala_dova_delegate_module_get_type ())
#define VALA_DOVA_DELEGATE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_DELEGATE_MODULE, ValaDovaDelegateModule))
#define VALA_DOVA_DELEGATE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_DELEGATE_MODULE, ValaDovaDelegateModuleClass))
#define VALA_IS_DOVA_DELEGATE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_DELEGATE_MODULE))
#define VALA_IS_DOVA_DELEGATE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_DELEGATE_MODULE))
#define VALA_DOVA_DELEGATE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_DELEGATE_MODULE, ValaDovaDelegateModuleClass))

typedef struct _ValaDovaDelegateModule ValaDovaDelegateModule;
typedef struct _ValaDovaDelegateModuleClass ValaDovaDelegateModuleClass;
typedef struct _ValaDovaDelegateModulePrivate ValaDovaDelegateModulePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_ccode_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_node_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_collection_object_unref0(var) ((var == NULL) ? NULL : (var = (vala_collection_object_unref (var), NULL)))

struct _ValaDovaBaseModule {
	ValaCodeGenerator parent_instance;
	ValaDovaBaseModulePrivate * priv;
	ValaSymbol* root_symbol;
	ValaDovaBaseModuleEmitContext* emit_context;
	ValaCCodeDeclarationSpace* header_declarations;
	ValaCCodeDeclarationSpace* source_declarations;
	ValaCCodeFragment* source_type_member_definition;
	ValaCCodeFragment* module_init_fragment;
	ValaCCodeFragment* instance_init_fragment;
	ValaCCodeFragment* instance_finalize_fragment;
	ValaCCodeFragment* pre_statement_fragment;
	gint next_wrapper_id;
	ValaDataType* void_type;
	ValaDataType* bool_type;
	ValaDataType* char_type;
	ValaDataType* short_type;
	ValaDataType* ushort_type;
	ValaDataType* int_type;
	ValaDataType* uint_type;
	ValaDataType* long_type;
	ValaDataType* ulong_type;
	ValaDataType* string_type;
	ValaDataType* float_type;
	ValaDataType* double_type;
	ValaClass* object_class;
	ValaClass* type_class;
	ValaClass* value_class;
	ValaClass* string_class;
	ValaClass* array_class;
	ValaClass* delegate_class;
	ValaClass* error_class;
};

struct _ValaDovaBaseModuleClass {
	ValaCodeGeneratorClass parent_class;
	void (*generate_struct_declaration) (ValaDovaBaseModule* self, ValaStruct* st, ValaCCodeDeclarationSpace* decl_space);
	void (*generate_delegate_declaration) (ValaDovaBaseModule* self, ValaDelegate* d, ValaCCodeDeclarationSpace* decl_space);
	void (*generate_cparameters) (ValaDovaBaseModule* self, ValaMethod* m, ValaCCodeDeclarationSpace* decl_space, ValaCCodeFunction* func, ValaCCodeFunctionDeclarator* vdeclarator, ValaCCodeFunctionCall* vcall);
	void (*generate_property_accessor_declaration) (ValaDovaBaseModule* self, ValaPropertyAccessor* acc, ValaCCodeDeclarationSpace* decl_space);
	ValaCCodeExpression* (*get_dup_func_expression) (ValaDovaBaseModule* self, ValaDataType* type, ValaSourceReference* source_reference, gboolean is_chainup);
	ValaCCodeExpression* (*get_unref_expression) (ValaDovaBaseModule* self, ValaCCodeExpression* cvar, ValaDataType* type, ValaExpression* expr);
	void (*append_local_free) (ValaDovaBaseModule* self, ValaSymbol* sym, ValaCCodeFragment* cfrag, gboolean stop_at_loop);
	ValaCCodeExpression* (*get_ref_cexpression) (ValaDovaBaseModule* self, ValaDataType* expression_type, ValaCCodeExpression* cexpr, ValaExpression* expr, ValaCodeNode* node);
	void (*generate_class_declaration) (ValaDovaBaseModule* self, ValaClass* cl, ValaCCodeDeclarationSpace* decl_space);
	void (*generate_interface_declaration) (ValaDovaBaseModule* self, ValaInterface* iface, ValaCCodeDeclarationSpace* decl_space);
	void (*generate_method_declaration) (ValaDovaBaseModule* self, ValaMethod* m, ValaCCodeDeclarationSpace* decl_space);
	ValaCCodeExpression* (*get_implicit_cast_expression) (ValaDovaBaseModule* self, ValaCCodeExpression* source_cexpr, ValaDataType* expression_type, ValaDataType* target_type, ValaExpression* expr);
	char* (*get_custom_creturn_type) (ValaDovaBaseModule* self, ValaMethod* m);
	gboolean (*method_has_wrapper) (ValaDovaBaseModule* self, ValaMethod* method);
	void (*add_simple_check) (ValaDovaBaseModule* self, ValaCodeNode* node, ValaCCodeFragment* cfrag, gboolean always_fails);
};

struct _ValaDovaStructModule {
	ValaDovaBaseModule parent_instance;
	ValaDovaStructModulePrivate * priv;
};

struct _ValaDovaStructModuleClass {
	ValaDovaBaseModuleClass parent_class;
};

struct _ValaDovaMethodModule {
	ValaDovaStructModule parent_instance;
	ValaDovaMethodModulePrivate * priv;
};

struct _ValaDovaMethodModuleClass {
	ValaDovaStructModuleClass parent_class;
};

struct _ValaDovaControlFlowModule {
	ValaDovaMethodModule parent_instance;
	ValaDovaControlFlowModulePrivate * priv;
};

struct _ValaDovaControlFlowModuleClass {
	ValaDovaMethodModuleClass parent_class;
};

struct _ValaDovaMemberAccessModule {
	ValaDovaControlFlowModule parent_instance;
	ValaDovaMemberAccessModulePrivate * priv;
};

struct _ValaDovaMemberAccessModuleClass {
	ValaDovaControlFlowModuleClass parent_class;
};

struct _ValaDovaAssignmentModule {
	ValaDovaMemberAccessModule parent_instance;
	ValaDovaAssignmentModulePrivate * priv;
};

struct _ValaDovaAssignmentModuleClass {
	ValaDovaMemberAccessModuleClass parent_class;
};

struct _ValaDovaMethodCallModule {
	ValaDovaAssignmentModule parent_instance;
	ValaDovaMethodCallModulePrivate * priv;
};

struct _ValaDovaMethodCallModuleClass {
	ValaDovaAssignmentModuleClass parent_class;
};

struct _ValaDovaArrayModule {
	ValaDovaMethodCallModule parent_instance;
	ValaDovaArrayModulePrivate * priv;
};

struct _ValaDovaArrayModuleClass {
	ValaDovaMethodCallModuleClass parent_class;
};

struct _ValaDovaObjectModule {
	ValaDovaArrayModule parent_instance;
	ValaDovaObjectModulePrivate * priv;
};

struct _ValaDovaObjectModuleClass {
	ValaDovaArrayModuleClass parent_class;
};

struct _ValaDovaValueModule {
	ValaDovaObjectModule parent_instance;
	ValaDovaValueModulePrivate * priv;
};

struct _ValaDovaValueModuleClass {
	ValaDovaObjectModuleClass parent_class;
};

struct _ValaDovaDelegateModule {
	ValaDovaValueModule parent_instance;
	ValaDovaDelegateModulePrivate * priv;
};

struct _ValaDovaDelegateModuleClass {
	ValaDovaValueModuleClass parent_class;
};


static gpointer vala_dova_delegate_module_parent_class = NULL;

GType vala_dova_base_module_get_type (void) G_GNUC_CONST;
gpointer vala_ccode_declaration_space_ref (gpointer instance);
void vala_ccode_declaration_space_unref (gpointer instance);
GParamSpec* vala_param_spec_ccode_declaration_space (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void vala_value_set_ccode_declaration_space (GValue* value, gpointer v_object);
void vala_value_take_ccode_declaration_space (GValue* value, gpointer v_object);
gpointer vala_value_get_ccode_declaration_space (const GValue* value);
GType vala_ccode_declaration_space_get_type (void) G_GNUC_CONST;
gpointer vala_dova_base_module_emit_context_ref (gpointer instance);
void vala_dova_base_module_emit_context_unref (gpointer instance);
GParamSpec* vala_dova_base_module_param_spec_emit_context (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void vala_dova_base_module_value_set_emit_context (GValue* value, gpointer v_object);
void vala_dova_base_module_value_take_emit_context (GValue* value, gpointer v_object);
gpointer vala_dova_base_module_value_get_emit_context (const GValue* value);
GType vala_dova_base_module_emit_context_get_type (void) G_GNUC_CONST;
GType vala_dova_struct_module_get_type (void) G_GNUC_CONST;
GType vala_dova_method_module_get_type (void) G_GNUC_CONST;
GType vala_dova_control_flow_module_get_type (void) G_GNUC_CONST;
GType vala_dova_member_access_module_get_type (void) G_GNUC_CONST;
GType vala_dova_assignment_module_get_type (void) G_GNUC_CONST;
GType vala_dova_method_call_module_get_type (void) G_GNUC_CONST;
GType vala_dova_array_module_get_type (void) G_GNUC_CONST;
GType vala_dova_object_module_get_type (void) G_GNUC_CONST;
GType vala_dova_value_module_get_type (void) G_GNUC_CONST;
GType vala_dova_delegate_module_get_type (void) G_GNUC_CONST;
enum  {
	VALA_DOVA_DELEGATE_MODULE_DUMMY_PROPERTY
};
static void vala_dova_delegate_module_real_generate_delegate_declaration (ValaDovaBaseModule* base, ValaDelegate* d, ValaCCodeDeclarationSpace* decl_space);
gboolean vala_ccode_declaration_space_add_symbol_declaration (ValaCCodeDeclarationSpace* self, ValaSymbol* sym, const char* name);
void vala_ccode_declaration_space_add_type_declaration (ValaCCodeDeclarationSpace* self, ValaCCodeNode* node);
void vala_dova_base_module_generate_class_declaration (ValaDovaBaseModule* self, ValaClass* cl, ValaCCodeDeclarationSpace* decl_space);
void vala_dova_base_module_generate_method_declaration (ValaDovaBaseModule* self, ValaMethod* m, ValaCCodeDeclarationSpace* decl_space);
void vala_ccode_declaration_space_add_type_member_declaration (ValaCCodeDeclarationSpace* self, ValaCCodeNode* node);
void vala_dova_base_module_generate_type_declaration (ValaDovaBaseModule* self, ValaDataType* type, ValaCCodeDeclarationSpace* decl_space);
static ValaCCodeFunction* vala_dova_delegate_module_generate_new_function (ValaDovaDelegateModule* self, ValaDelegate* d, ValaCCodeDeclarationSpace* decl_space);
static ValaCCodeFunction* vala_dova_delegate_module_generate_invoke_function (ValaDovaDelegateModule* self, ValaDelegate* d, ValaCCodeDeclarationSpace* decl_space);
static void vala_dova_delegate_module_real_visit_delegate (ValaCodeVisitor* base, ValaDelegate* d);
void vala_dova_base_module_generate_delegate_declaration (ValaDovaBaseModule* self, ValaDelegate* d, ValaCCodeDeclarationSpace* decl_space);
ValaCCodeBlock* vala_dova_object_module_generate_type_get_function (ValaDovaObjectModule* self, ValaTypeSymbol* cl, ValaClass* base_class);
void vala_ccode_declaration_space_add_type_definition (ValaCCodeDeclarationSpace* self, ValaCCodeNode* node);
ValaDovaDelegateModule* vala_dova_delegate_module_new (void);
ValaDovaDelegateModule* vala_dova_delegate_module_construct (GType object_type);
ValaDovaValueModule* vala_dova_value_module_new (void);
ValaDovaValueModule* vala_dova_value_module_construct (GType object_type);
static int _vala_strcmp0 (const char * str1, const char * str2);



static void vala_dova_delegate_module_real_generate_delegate_declaration (ValaDovaBaseModule* base, ValaDelegate* d, ValaCCodeDeclarationSpace* decl_space) {
	ValaDovaDelegateModule * self;
	char* _tmp0_;
	gboolean _tmp1_;
	char* _tmp2_;
	char* _tmp3_;
	char* _tmp4_;
	ValaCCodeVariableDeclarator* _tmp5_;
	ValaCCodeTypeDefinition* _tmp6_;
	ValaMethod* _tmp7_;
	ValaMethod* _tmp8_;
	char* _tmp9_;
	char* _tmp10_;
	ValaCCodeFunction* _tmp11_;
	ValaCCodeFunction* type_fun;
	char* _tmp12_;
	char* _tmp13_;
	ValaCCodeFunction* _tmp14_;
	ValaCCodeFunction* type_init_fun;
	ValaCCodeFormalParameter* _tmp15_;
	ValaCCodeFunction* function;
	ValaCCodeFunction* _tmp16_;
	self = (ValaDovaDelegateModule*) base;
	g_return_if_fail (d != NULL);
	g_return_if_fail (decl_space != NULL);
	if ((_tmp1_ = vala_ccode_declaration_space_add_symbol_declaration (decl_space, (ValaSymbol*) d, _tmp0_ = vala_typesymbol_get_cname ((ValaTypeSymbol*) d, FALSE)), _g_free0 (_tmp0_), _tmp1_)) {
		return;
	}
	vala_ccode_declaration_space_add_type_declaration (decl_space, (ValaCCodeNode*) (_tmp6_ = vala_ccode_type_definition_new (_tmp3_ = g_strdup_printf ("struct _%s", _tmp2_ = vala_typesymbol_get_cname ((ValaTypeSymbol*) d, FALSE)), (ValaCCodeDeclarator*) (_tmp5_ = vala_ccode_variable_declarator_new (_tmp4_ = vala_typesymbol_get_cname ((ValaTypeSymbol*) d, FALSE), NULL, NULL)))));
	_vala_ccode_node_unref0 (_tmp6_);
	_vala_ccode_node_unref0 (_tmp5_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp3_);
	_g_free0 (_tmp2_);
	vala_dova_base_module_generate_class_declaration ((ValaDovaBaseModule*) self, ((ValaDovaBaseModule*) self)->type_class, decl_space);
	vala_dova_base_module_generate_method_declaration ((ValaDovaBaseModule*) self, _tmp7_ = VALA_METHOD (vala_scope_lookup (vala_symbol_get_scope ((ValaSymbol*) ((ValaDovaBaseModule*) self)->object_class), "ref")), decl_space);
	_vala_code_node_unref0 (_tmp7_);
	vala_dova_base_module_generate_method_declaration ((ValaDovaBaseModule*) self, _tmp8_ = VALA_METHOD (vala_scope_lookup (vala_symbol_get_scope ((ValaSymbol*) ((ValaDovaBaseModule*) self)->object_class), "unref")), decl_space);
	_vala_code_node_unref0 (_tmp8_);
	type_fun = (_tmp11_ = vala_ccode_function_new (_tmp10_ = g_strdup_printf ("%s_type_get", _tmp9_ = vala_symbol_get_lower_case_cname ((ValaSymbol*) d, NULL)), "DovaType *"), _g_free0 (_tmp10_), _g_free0 (_tmp9_), _tmp11_);
	if (vala_symbol_is_internal_symbol ((ValaSymbol*) d)) {
		vala_ccode_function_set_modifiers (type_fun, VALA_CCODE_MODIFIERS_STATIC);
	}
	vala_ccode_declaration_space_add_type_member_declaration (decl_space, (ValaCCodeNode*) type_fun);
	type_init_fun = (_tmp14_ = vala_ccode_function_new (_tmp13_ = g_strdup_printf ("%s_type_init", _tmp12_ = vala_symbol_get_lower_case_cname ((ValaSymbol*) d, NULL)), "void"), _g_free0 (_tmp13_), _g_free0 (_tmp12_), _tmp14_);
	if (vala_symbol_is_internal_symbol ((ValaSymbol*) d)) {
		vala_ccode_function_set_modifiers (type_init_fun, VALA_CCODE_MODIFIERS_STATIC);
	}
	vala_ccode_function_add_parameter (type_init_fun, _tmp15_ = vala_ccode_formal_parameter_new ("type", "DovaType *"));
	_vala_ccode_node_unref0 (_tmp15_);
	vala_ccode_declaration_space_add_type_member_declaration (decl_space, (ValaCCodeNode*) type_init_fun);
	vala_dova_base_module_generate_type_declaration ((ValaDovaBaseModule*) self, vala_delegate_get_return_type (d), decl_space);
	function = vala_dova_delegate_module_generate_new_function (self, d, decl_space);
	vala_ccode_function_set_block (function, NULL);
	vala_ccode_declaration_space_add_type_member_declaration (decl_space, (ValaCCodeNode*) function);
	function = (_tmp16_ = vala_dova_delegate_module_generate_invoke_function (self, d, decl_space), _vala_ccode_node_unref0 (function), _tmp16_);
	vala_ccode_function_set_block (function, NULL);
	vala_ccode_declaration_space_add_type_member_declaration (decl_space, (ValaCCodeNode*) function);
	_vala_ccode_node_unref0 (function);
	_vala_ccode_node_unref0 (type_init_fun);
	_vala_ccode_node_unref0 (type_fun);
}


static ValaCCodeFunction* vala_dova_delegate_module_generate_new_function (ValaDovaDelegateModule* self, ValaDelegate* d, ValaCCodeDeclarationSpace* decl_space) {
	ValaCCodeFunction* result = NULL;
	char* _tmp0_;
	char* _tmp1_;
	char* _tmp2_;
	char* _tmp3_;
	ValaCCodeFunction* _tmp4_;
	ValaCCodeFunction* function;
	ValaCCodeFormalParameter* _tmp5_;
	ValaCCodeFormalParameter* _tmp6_;
	ValaCCodeBlock* _tmp7_;
	ValaCCodeIdentifier* _tmp8_;
	ValaCCodeFunctionCall* _tmp9_;
	ValaCCodeFunctionCall* alloc_call;
	char* _tmp10_;
	char* _tmp11_;
	ValaCCodeIdentifier* _tmp12_;
	ValaCCodeFunctionCall* _tmp13_;
	char* _tmp14_;
	char* _tmp15_;
	ValaCCodeDeclaration* _tmp16_;
	ValaCCodeDeclaration* _cdecl_;
	ValaCCodeVariableDeclarator* _tmp17_;
	ValaCCodeIdentifier* _tmp18_;
	ValaCCodeFunctionCall* _tmp19_;
	ValaCCodeFunctionCall* init_call;
	ValaCCodeIdentifier* _tmp20_;
	ValaCCodeIdentifier* _tmp21_;
	ValaCCodeExpressionStatement* _tmp22_;
	char* _tmp23_;
	char* _tmp24_;
	ValaCCodeIdentifier* _tmp25_;
	ValaCCodeFunctionCall* _tmp26_;
	ValaCCodeFunctionCall* priv;
	ValaCCodeIdentifier* _tmp27_;
	ValaCCodeMemberAccess* _tmp28_;
	ValaCCodeIdentifier* _tmp29_;
	ValaCCodeAssignment* _tmp30_;
	ValaCCodeAssignment* assignment;
	ValaCCodeExpressionStatement* _tmp31_;
	ValaCCodeIdentifier* _tmp32_;
	ValaCCodeReturnStatement* _tmp33_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (d != NULL, NULL);
	g_return_val_if_fail (decl_space != NULL, NULL);
	function = (_tmp4_ = vala_ccode_function_new (_tmp1_ = g_strdup_printf ("%s_new", _tmp0_ = vala_symbol_get_lower_case_cname ((ValaSymbol*) d, NULL)), _tmp3_ = g_strdup_printf ("%s*", _tmp2_ = vala_typesymbol_get_cname ((ValaTypeSymbol*) d, FALSE))), _g_free0 (_tmp3_), _g_free0 (_tmp2_), _g_free0 (_tmp1_), _g_free0 (_tmp0_), _tmp4_);
	if (vala_symbol_is_internal_symbol ((ValaSymbol*) d)) {
		vala_ccode_function_set_modifiers (function, vala_ccode_function_get_modifiers (function) | VALA_CCODE_MODIFIERS_STATIC);
	}
	vala_ccode_function_add_parameter (function, _tmp5_ = vala_ccode_formal_parameter_new ("target", "DovaObject *"));
	_vala_ccode_node_unref0 (_tmp5_);
	vala_ccode_function_add_parameter (function, _tmp6_ = vala_ccode_formal_parameter_new ("(*method) (void)", "void"));
	_vala_ccode_node_unref0 (_tmp6_);
	vala_ccode_function_set_block (function, _tmp7_ = vala_ccode_block_new ());
	_vala_ccode_node_unref0 (_tmp7_);
	alloc_call = (_tmp9_ = vala_ccode_function_call_new ((ValaCCodeExpression*) (_tmp8_ = vala_ccode_identifier_new ("dova_object_alloc"))), _vala_ccode_node_unref0 (_tmp8_), _tmp9_);
	vala_ccode_function_call_add_argument (alloc_call, (ValaCCodeExpression*) (_tmp13_ = vala_ccode_function_call_new ((ValaCCodeExpression*) (_tmp12_ = vala_ccode_identifier_new (_tmp11_ = g_strdup_printf ("%s_type_get", _tmp10_ = vala_symbol_get_lower_case_cname ((ValaSymbol*) d, NULL)))))));
	_vala_ccode_node_unref0 (_tmp13_);
	_vala_ccode_node_unref0 (_tmp12_);
	_g_free0 (_tmp11_);
	_g_free0 (_tmp10_);
	_cdecl_ = (_tmp16_ = vala_ccode_declaration_new (_tmp15_ = g_strdup_printf ("%s*", _tmp14_ = vala_typesymbol_get_cname ((ValaTypeSymbol*) d, FALSE))), _g_free0 (_tmp15_), _g_free0 (_tmp14_), _tmp16_);
	vala_ccode_declaration_add_declarator (_cdecl_, (ValaCCodeDeclarator*) (_tmp17_ = vala_ccode_variable_declarator_new ("this", (ValaCCodeExpression*) alloc_call, NULL)));
	_vala_ccode_node_unref0 (_tmp17_);
	vala_ccode_block_add_statement (vala_ccode_function_get_block (function), (ValaCCodeNode*) _cdecl_);
	init_call = (_tmp19_ = vala_ccode_function_call_new ((ValaCCodeExpression*) (_tmp18_ = vala_ccode_identifier_new ("dova_delegate_init"))), _vala_ccode_node_unref0 (_tmp18_), _tmp19_);
	vala_ccode_function_call_add_argument (init_call, (ValaCCodeExpression*) (_tmp20_ = vala_ccode_identifier_new ("this")));
	_vala_ccode_node_unref0 (_tmp20_);
	vala_ccode_function_call_add_argument (init_call, (ValaCCodeExpression*) (_tmp21_ = vala_ccode_identifier_new ("target")));
	_vala_ccode_node_unref0 (_tmp21_);
	vala_ccode_block_add_statement (vala_ccode_function_get_block (function), (ValaCCodeNode*) (_tmp22_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) init_call)));
	_vala_ccode_node_unref0 (_tmp22_);
	priv = (_tmp26_ = vala_ccode_function_call_new ((ValaCCodeExpression*) (_tmp25_ = vala_ccode_identifier_new (_tmp24_ = g_strdup_printf ("%s_GET_PRIVATE", _tmp23_ = vala_typesymbol_get_upper_case_cname ((ValaTypeSymbol*) d, NULL))))), _vala_ccode_node_unref0 (_tmp25_), _g_free0 (_tmp24_), _g_free0 (_tmp23_), _tmp26_);
	vala_ccode_function_call_add_argument (priv, (ValaCCodeExpression*) (_tmp27_ = vala_ccode_identifier_new ("this")));
	_vala_ccode_node_unref0 (_tmp27_);
	assignment = (_tmp30_ = vala_ccode_assignment_new ((ValaCCodeExpression*) (_tmp28_ = vala_ccode_member_access_new_pointer ((ValaCCodeExpression*) priv, "method")), (ValaCCodeExpression*) (_tmp29_ = vala_ccode_identifier_new ("method")), VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE), _vala_ccode_node_unref0 (_tmp29_), _vala_ccode_node_unref0 (_tmp28_), _tmp30_);
	vala_ccode_block_add_statement (vala_ccode_function_get_block (function), (ValaCCodeNode*) (_tmp31_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) assignment)));
	_vala_ccode_node_unref0 (_tmp31_);
	vala_ccode_block_add_statement (vala_ccode_function_get_block (function), (ValaCCodeNode*) (_tmp33_ = vala_ccode_return_statement_new ((ValaCCodeExpression*) (_tmp32_ = vala_ccode_identifier_new ("this")))));
	_vala_ccode_node_unref0 (_tmp33_);
	_vala_ccode_node_unref0 (_tmp32_);
	result = function;
	_vala_ccode_node_unref0 (assignment);
	_vala_ccode_node_unref0 (priv);
	_vala_ccode_node_unref0 (init_call);
	_vala_ccode_node_unref0 (_cdecl_);
	_vala_ccode_node_unref0 (alloc_call);
	return result;
}


static ValaCCodeFunction* vala_dova_delegate_module_generate_invoke_function (ValaDovaDelegateModule* self, ValaDelegate* d, ValaCCodeDeclarationSpace* decl_space) {
	ValaCCodeFunction* result = NULL;
	char* _tmp0_;
	char* _tmp1_;
	ValaCCodeFunction* _tmp2_;
	ValaCCodeFunction* function;
	char* _tmp3_;
	char* _tmp4_;
	ValaCCodeFormalParameter* _tmp5_;
	char* param_list;
	ValaCCodeBlock* _tmp17_;
	ValaCCodeIdentifier* _tmp18_;
	ValaCCodeFunctionCall* _tmp19_;
	ValaCCodeFunctionCall* get_target;
	ValaCCodeIdentifier* _tmp20_;
	ValaCCodeDeclaration* _cdecl_;
	ValaCCodeVariableDeclarator* _tmp21_;
	char* _tmp22_;
	char* _tmp23_;
	ValaCCodeIdentifier* _tmp24_;
	ValaCCodeFunctionCall* _tmp25_;
	ValaCCodeFunctionCall* priv;
	ValaCCodeIdentifier* _tmp26_;
	char* instance_param_list;
	char* _tmp29_;
	ValaCCodeBlock* instance_block;
	ValaCCodeMemberAccess* _tmp30_;
	char* _tmp31_;
	ValaCCodeCastExpression* _tmp32_;
	ValaCCodeFunctionCall* _tmp33_;
	ValaCCodeFunctionCall* instance_call;
	ValaCCodeIdentifier* _tmp34_;
	char* static_param_list;
	char* _tmp37_;
	ValaCCodeBlock* static_block;
	ValaCCodeMemberAccess* _tmp38_;
	char* _tmp39_;
	ValaCCodeCastExpression* _tmp40_;
	ValaCCodeFunctionCall* _tmp41_;
	ValaCCodeFunctionCall* static_call;
	ValaCCodeIdentifier* _tmp54_;
	ValaCCodeIfStatement* _tmp55_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (d != NULL, NULL);
	g_return_val_if_fail (decl_space != NULL, NULL);
	function = (_tmp2_ = vala_ccode_function_new (_tmp1_ = g_strdup_printf ("%s_invoke", _tmp0_ = vala_symbol_get_lower_case_cname ((ValaSymbol*) d, NULL)), "void"), _g_free0 (_tmp1_), _g_free0 (_tmp0_), _tmp2_);
	if (vala_symbol_is_internal_symbol ((ValaSymbol*) d)) {
		vala_ccode_function_set_modifiers (function, vala_ccode_function_get_modifiers (function) | VALA_CCODE_MODIFIERS_STATIC);
	}
	vala_ccode_function_add_parameter (function, _tmp5_ = vala_ccode_formal_parameter_new ("this", _tmp4_ = g_strdup_printf ("%s*", _tmp3_ = vala_typesymbol_get_cname ((ValaTypeSymbol*) d, FALSE))));
	_vala_ccode_node_unref0 (_tmp5_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp3_);
	param_list = g_strdup ("");
	{
		ValaList* _tmp6_;
		ValaIterator* _tmp7_;
		ValaIterator* _param_it;
		_param_it = (_tmp7_ = vala_iterable_iterator ((ValaIterable*) (_tmp6_ = vala_delegate_get_parameters (d))), _vala_collection_object_unref0 (_tmp6_), _tmp7_);
		while (TRUE) {
			ValaFormalParameter* param;
			char* _tmp8_;
			ValaCCodeFormalParameter* _tmp9_;
			char* _tmp11_;
			char* _tmp12_;
			if (!vala_iterator_next (_param_it)) {
				break;
			}
			param = (ValaFormalParameter*) vala_iterator_get (_param_it);
			vala_dova_base_module_generate_type_declaration ((ValaDovaBaseModule*) self, vala_variable_get_variable_type ((ValaVariable*) param), decl_space);
			vala_ccode_function_add_parameter (function, _tmp9_ = vala_ccode_formal_parameter_new (vala_symbol_get_name ((ValaSymbol*) param), _tmp8_ = vala_data_type_get_cname (vala_variable_get_variable_type ((ValaVariable*) param))));
			_vala_ccode_node_unref0 (_tmp9_);
			_g_free0 (_tmp8_);
			if (_vala_strcmp0 (param_list, "") != 0) {
				char* _tmp10_;
				param_list = (_tmp10_ = g_strconcat (param_list, ", ", NULL), _g_free0 (param_list), _tmp10_);
			}
			param_list = (_tmp12_ = g_strconcat (param_list, _tmp11_ = vala_data_type_get_cname (vala_variable_get_variable_type ((ValaVariable*) param)), NULL), _g_free0 (param_list), _tmp12_);
			_g_free0 (_tmp11_);
			_vala_code_node_unref0 (param);
		}
		_vala_collection_object_unref0 (_param_it);
	}
	if (VALA_IS_GENERIC_TYPE (vala_delegate_get_return_type (d))) {
		ValaCCodeFormalParameter* _tmp13_;
		char* _tmp15_;
		vala_ccode_function_add_parameter (function, _tmp13_ = vala_ccode_formal_parameter_new ("result", "void *"));
		_vala_ccode_node_unref0 (_tmp13_);
		if (_vala_strcmp0 (param_list, "") != 0) {
			char* _tmp14_;
			param_list = (_tmp14_ = g_strconcat (param_list, ", ", NULL), _g_free0 (param_list), _tmp14_);
		}
		param_list = (_tmp15_ = g_strconcat (param_list, "void *", NULL), _g_free0 (param_list), _tmp15_);
	} else {
		char* _tmp16_;
		vala_ccode_function_set_return_type (function, _tmp16_ = vala_data_type_get_cname (vala_delegate_get_return_type (d)));
		_g_free0 (_tmp16_);
	}
	vala_ccode_function_set_block (function, _tmp17_ = vala_ccode_block_new ());
	_vala_ccode_node_unref0 (_tmp17_);
	get_target = (_tmp19_ = vala_ccode_function_call_new ((ValaCCodeExpression*) (_tmp18_ = vala_ccode_identifier_new ("dova_delegate_get_target"))), _vala_ccode_node_unref0 (_tmp18_), _tmp19_);
	vala_ccode_function_call_add_argument (get_target, (ValaCCodeExpression*) (_tmp20_ = vala_ccode_identifier_new ("this")));
	_vala_ccode_node_unref0 (_tmp20_);
	_cdecl_ = vala_ccode_declaration_new ("DovaObject*");
	vala_ccode_declaration_add_declarator (_cdecl_, (ValaCCodeDeclarator*) (_tmp21_ = vala_ccode_variable_declarator_new ("target", (ValaCCodeExpression*) get_target, NULL)));
	_vala_ccode_node_unref0 (_tmp21_);
	vala_ccode_block_add_statement (vala_ccode_function_get_block (function), (ValaCCodeNode*) _cdecl_);
	priv = (_tmp25_ = vala_ccode_function_call_new ((ValaCCodeExpression*) (_tmp24_ = vala_ccode_identifier_new (_tmp23_ = g_strdup_printf ("%s_GET_PRIVATE", _tmp22_ = vala_typesymbol_get_upper_case_cname ((ValaTypeSymbol*) d, NULL))))), _vala_ccode_node_unref0 (_tmp24_), _g_free0 (_tmp23_), _g_free0 (_tmp22_), _tmp25_);
	vala_ccode_function_call_add_argument (priv, (ValaCCodeExpression*) (_tmp26_ = vala_ccode_identifier_new ("this")));
	_vala_ccode_node_unref0 (_tmp26_);
	instance_param_list = g_strdup ("(DovaObject *");
	if (_vala_strcmp0 (param_list, "") != 0) {
		char* _tmp27_;
		char* _tmp28_;
		instance_param_list = (_tmp27_ = g_strconcat (instance_param_list, ",", NULL), _g_free0 (instance_param_list), _tmp27_);
		instance_param_list = (_tmp28_ = g_strconcat (instance_param_list, param_list, NULL), _g_free0 (instance_param_list), _tmp28_);
	}
	instance_param_list = (_tmp29_ = g_strconcat (instance_param_list, ")", NULL), _g_free0 (instance_param_list), _tmp29_);
	instance_block = vala_ccode_block_new ();
	instance_call = (_tmp33_ = vala_ccode_function_call_new ((ValaCCodeExpression*) (_tmp32_ = vala_ccode_cast_expression_new ((ValaCCodeExpression*) (_tmp30_ = vala_ccode_member_access_new_pointer ((ValaCCodeExpression*) priv, "method")), _tmp31_ = g_strdup_printf ("%s (*) %s", vala_ccode_function_get_return_type (function), instance_param_list)))), _vala_ccode_node_unref0 (_tmp32_), _g_free0 (_tmp31_), _vala_ccode_node_unref0 (_tmp30_), _tmp33_);
	vala_ccode_function_call_add_argument (instance_call, (ValaCCodeExpression*) (_tmp34_ = vala_ccode_identifier_new ("target")));
	_vala_ccode_node_unref0 (_tmp34_);
	static_param_list = g_strdup ("(");
	if (_vala_strcmp0 (param_list, "") != 0) {
		char* _tmp35_;
		static_param_list = (_tmp35_ = g_strconcat (static_param_list, param_list, NULL), _g_free0 (static_param_list), _tmp35_);
	} else {
		char* _tmp36_;
		static_param_list = (_tmp36_ = g_strconcat (static_param_list, "void", NULL), _g_free0 (static_param_list), _tmp36_);
	}
	static_param_list = (_tmp37_ = g_strconcat (static_param_list, ")", NULL), _g_free0 (static_param_list), _tmp37_);
	static_block = vala_ccode_block_new ();
	static_call = (_tmp41_ = vala_ccode_function_call_new ((ValaCCodeExpression*) (_tmp40_ = vala_ccode_cast_expression_new ((ValaCCodeExpression*) (_tmp38_ = vala_ccode_member_access_new_pointer ((ValaCCodeExpression*) priv, "method")), _tmp39_ = g_strdup_printf ("%s (*) %s", vala_ccode_function_get_return_type (function), static_param_list)))), _vala_ccode_node_unref0 (_tmp40_), _g_free0 (_tmp39_), _vala_ccode_node_unref0 (_tmp38_), _tmp41_);
	{
		ValaList* _tmp42_;
		ValaIterator* _tmp43_;
		ValaIterator* _param_it;
		_param_it = (_tmp43_ = vala_iterable_iterator ((ValaIterable*) (_tmp42_ = vala_delegate_get_parameters (d))), _vala_collection_object_unref0 (_tmp42_), _tmp43_);
		while (TRUE) {
			ValaFormalParameter* param;
			ValaCCodeIdentifier* _tmp44_;
			ValaCCodeIdentifier* _tmp45_;
			if (!vala_iterator_next (_param_it)) {
				break;
			}
			param = (ValaFormalParameter*) vala_iterator_get (_param_it);
			vala_ccode_function_call_add_argument (instance_call, (ValaCCodeExpression*) (_tmp44_ = vala_ccode_identifier_new (vala_symbol_get_name ((ValaSymbol*) param))));
			_vala_ccode_node_unref0 (_tmp44_);
			vala_ccode_function_call_add_argument (static_call, (ValaCCodeExpression*) (_tmp45_ = vala_ccode_identifier_new (vala_symbol_get_name ((ValaSymbol*) param))));
			_vala_ccode_node_unref0 (_tmp45_);
			_vala_code_node_unref0 (param);
		}
		_vala_collection_object_unref0 (_param_it);
	}
	if (VALA_IS_VOID_TYPE (vala_delegate_get_return_type (d))) {
		ValaCCodeExpressionStatement* _tmp46_;
		ValaCCodeExpressionStatement* _tmp47_;
		vala_ccode_block_add_statement (instance_block, (ValaCCodeNode*) (_tmp46_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) instance_call)));
		_vala_ccode_node_unref0 (_tmp46_);
		vala_ccode_block_add_statement (static_block, (ValaCCodeNode*) (_tmp47_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) static_call)));
		_vala_ccode_node_unref0 (_tmp47_);
	} else {
		if (VALA_IS_GENERIC_TYPE (vala_delegate_get_return_type (d))) {
			ValaCCodeIdentifier* _tmp48_;
			ValaCCodeIdentifier* _tmp49_;
			ValaCCodeExpressionStatement* _tmp50_;
			ValaCCodeExpressionStatement* _tmp51_;
			vala_ccode_function_call_add_argument (instance_call, (ValaCCodeExpression*) (_tmp48_ = vala_ccode_identifier_new ("result")));
			_vala_ccode_node_unref0 (_tmp48_);
			vala_ccode_function_call_add_argument (static_call, (ValaCCodeExpression*) (_tmp49_ = vala_ccode_identifier_new ("result")));
			_vala_ccode_node_unref0 (_tmp49_);
			vala_ccode_block_add_statement (instance_block, (ValaCCodeNode*) (_tmp50_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) instance_call)));
			_vala_ccode_node_unref0 (_tmp50_);
			vala_ccode_block_add_statement (static_block, (ValaCCodeNode*) (_tmp51_ = vala_ccode_expression_statement_new ((ValaCCodeExpression*) static_call)));
			_vala_ccode_node_unref0 (_tmp51_);
		} else {
			ValaCCodeReturnStatement* _tmp52_;
			ValaCCodeReturnStatement* _tmp53_;
			vala_ccode_block_add_statement (instance_block, (ValaCCodeNode*) (_tmp52_ = vala_ccode_return_statement_new ((ValaCCodeExpression*) instance_call)));
			_vala_ccode_node_unref0 (_tmp52_);
			vala_ccode_block_add_statement (static_block, (ValaCCodeNode*) (_tmp53_ = vala_ccode_return_statement_new ((ValaCCodeExpression*) static_call)));
			_vala_ccode_node_unref0 (_tmp53_);
		}
	}
	vala_ccode_block_add_statement (vala_ccode_function_get_block (function), (ValaCCodeNode*) (_tmp55_ = vala_ccode_if_statement_new ((ValaCCodeExpression*) (_tmp54_ = vala_ccode_identifier_new ("target")), (ValaCCodeStatement*) instance_block, (ValaCCodeStatement*) static_block)));
	_vala_ccode_node_unref0 (_tmp55_);
	_vala_ccode_node_unref0 (_tmp54_);
	result = function;
	_vala_ccode_node_unref0 (static_call);
	_vala_ccode_node_unref0 (static_block);
	_g_free0 (static_param_list);
	_vala_ccode_node_unref0 (instance_call);
	_vala_ccode_node_unref0 (instance_block);
	_g_free0 (instance_param_list);
	_vala_ccode_node_unref0 (priv);
	_vala_ccode_node_unref0 (_cdecl_);
	_vala_ccode_node_unref0 (get_target);
	_g_free0 (param_list);
	return result;
}


static void vala_dova_delegate_module_real_visit_delegate (ValaCodeVisitor* base, ValaDelegate* d) {
	ValaDovaDelegateModule * self;
	ValaCCodeBlock* _tmp0_;
	char* _tmp1_;
	char* _tmp2_;
	ValaCCodeStruct* _tmp3_;
	ValaCCodeStruct* instance_priv_struct;
	char* _tmp4_;
	char* _tmp5_;
	char* _tmp6_;
	ValaCCodeVariableDeclarator* _tmp7_;
	ValaCCodeTypeDefinition* _tmp8_;
	char* _tmp9_;
	char* _tmp10_;
	char* _tmp11_;
	char* macro;
	char* _tmp12_;
	char* _tmp13_;
	ValaCCodeMacroReplacement* _tmp14_;
	ValaCCodeDeclaration* _cdecl_;
	char* _tmp15_;
	char* _tmp16_;
	ValaCCodeConstant* _tmp17_;
	ValaCCodeVariableDeclarator* _tmp18_;
	ValaCCodeDeclaration* _tmp19_;
	char* _tmp20_;
	char* _tmp21_;
	ValaCCodeConstant* _tmp22_;
	ValaCCodeVariableDeclarator* _tmp23_;
	ValaCCodeFunction* _tmp24_;
	ValaCCodeFunction* _tmp25_;
	self = (ValaDovaDelegateModule*) base;
	g_return_if_fail (d != NULL);
	vala_code_node_accept_children ((ValaCodeNode*) d, (ValaCodeVisitor*) self);
	vala_dova_base_module_generate_delegate_declaration ((ValaDovaBaseModule*) self, d, ((ValaDovaBaseModule*) self)->source_declarations);
	if (!vala_symbol_is_internal_symbol ((ValaSymbol*) d)) {
		vala_dova_base_module_generate_delegate_declaration ((ValaDovaBaseModule*) self, d, ((ValaDovaBaseModule*) self)->header_declarations);
	}
	_tmp0_ = vala_dova_object_module_generate_type_get_function ((ValaDovaObjectModule*) self, (ValaTypeSymbol*) d, ((ValaDovaBaseModule*) self)->delegate_class);
	_vala_ccode_node_unref0 (_tmp0_);
	instance_priv_struct = (_tmp3_ = vala_ccode_struct_new (_tmp2_ = g_strdup_printf ("_%sPrivate", _tmp1_ = vala_typesymbol_get_cname ((ValaTypeSymbol*) d, FALSE))), _g_free0 (_tmp2_), _g_free0 (_tmp1_), _tmp3_);
	vala_ccode_struct_add_field (instance_priv_struct, "void", "(*method) (void)", NULL);
	vala_ccode_declaration_space_add_type_declaration (((ValaDovaBaseModule*) self)->source_declarations, (ValaCCodeNode*) (_tmp8_ = vala_ccode_type_definition_new (_tmp4_ = g_strdup_printf ("struct %s", vala_ccode_struct_get_name (instance_priv_struct)), (ValaCCodeDeclarator*) (_tmp7_ = vala_ccode_variable_declarator_new (_tmp6_ = g_strdup_printf ("%sPrivate", _tmp5_ = vala_typesymbol_get_cname ((ValaTypeSymbol*) d, FALSE)), NULL, NULL)))));
	_vala_ccode_node_unref0 (_tmp8_);
	_vala_ccode_node_unref0 (_tmp7_);
	_g_free0 (_tmp6_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp4_);
	vala_ccode_declaration_space_add_type_definition (((ValaDovaBaseModule*) self)->source_declarations, (ValaCCodeNode*) instance_priv_struct);
	macro = (_tmp11_ = g_strdup_printf ("((%sPrivate *) (((char *) o) + _%s_object_offset))", _tmp9_ = vala_typesymbol_get_cname ((ValaTypeSymbol*) d, FALSE), _tmp10_ = vala_symbol_get_lower_case_cname ((ValaSymbol*) d, NULL)), _g_free0 (_tmp10_), _g_free0 (_tmp9_), _tmp11_);
	vala_ccode_declaration_space_add_type_member_declaration (((ValaDovaBaseModule*) self)->source_declarations, (ValaCCodeNode*) (_tmp14_ = vala_ccode_macro_replacement_new (_tmp13_ = g_strdup_printf ("%s_GET_PRIVATE(o)", _tmp12_ = vala_typesymbol_get_upper_case_cname ((ValaTypeSymbol*) d, NULL)), macro)));
	_vala_ccode_node_unref0 (_tmp14_);
	_g_free0 (_tmp13_);
	_g_free0 (_tmp12_);
	_cdecl_ = vala_ccode_declaration_new ("int");
	vala_ccode_declaration_add_declarator (_cdecl_, (ValaCCodeDeclarator*) (_tmp18_ = vala_ccode_variable_declarator_new (_tmp16_ = g_strdup_printf ("_%s_object_offset", _tmp15_ = vala_symbol_get_lower_case_cname ((ValaSymbol*) d, NULL)), (ValaCCodeExpression*) (_tmp17_ = vala_ccode_constant_new ("0")), NULL)));
	_vala_ccode_node_unref0 (_tmp18_);
	_vala_ccode_node_unref0 (_tmp17_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp15_);
	vala_ccode_declaration_set_modifiers (_cdecl_, VALA_CCODE_MODIFIERS_STATIC);
	vala_ccode_declaration_space_add_type_member_declaration (((ValaDovaBaseModule*) self)->source_declarations, (ValaCCodeNode*) _cdecl_);
	_cdecl_ = (_tmp19_ = vala_ccode_declaration_new ("int"), _vala_ccode_node_unref0 (_cdecl_), _tmp19_);
	vala_ccode_declaration_add_declarator (_cdecl_, (ValaCCodeDeclarator*) (_tmp23_ = vala_ccode_variable_declarator_new (_tmp21_ = g_strdup_printf ("_%s_type_offset", _tmp20_ = vala_symbol_get_lower_case_cname ((ValaSymbol*) d, NULL)), (ValaCCodeExpression*) (_tmp22_ = vala_ccode_constant_new ("0")), NULL)));
	_vala_ccode_node_unref0 (_tmp23_);
	_vala_ccode_node_unref0 (_tmp22_);
	_g_free0 (_tmp21_);
	_g_free0 (_tmp20_);
	vala_ccode_declaration_set_modifiers (_cdecl_, VALA_CCODE_MODIFIERS_STATIC);
	vala_ccode_declaration_space_add_type_member_declaration (((ValaDovaBaseModule*) self)->source_declarations, (ValaCCodeNode*) _cdecl_);
	vala_ccode_fragment_append (((ValaDovaBaseModule*) self)->source_type_member_definition, (ValaCCodeNode*) (_tmp24_ = vala_dova_delegate_module_generate_new_function (self, d, ((ValaDovaBaseModule*) self)->source_declarations)));
	_vala_ccode_node_unref0 (_tmp24_);
	vala_ccode_fragment_append (((ValaDovaBaseModule*) self)->source_type_member_definition, (ValaCCodeNode*) (_tmp25_ = vala_dova_delegate_module_generate_invoke_function (self, d, ((ValaDovaBaseModule*) self)->source_declarations)));
	_vala_ccode_node_unref0 (_tmp25_);
	_vala_ccode_node_unref0 (_cdecl_);
	_g_free0 (macro);
	_vala_ccode_node_unref0 (instance_priv_struct);
}


ValaDovaDelegateModule* vala_dova_delegate_module_construct (GType object_type) {
	ValaDovaDelegateModule* self = NULL;
	self = (ValaDovaDelegateModule*) vala_dova_value_module_construct (object_type);
	return self;
}


ValaDovaDelegateModule* vala_dova_delegate_module_new (void) {
	return vala_dova_delegate_module_construct (VALA_TYPE_DOVA_DELEGATE_MODULE);
}


static void vala_dova_delegate_module_class_init (ValaDovaDelegateModuleClass * klass) {
	vala_dova_delegate_module_parent_class = g_type_class_peek_parent (klass);
	VALA_DOVA_BASE_MODULE_CLASS (klass)->generate_delegate_declaration = vala_dova_delegate_module_real_generate_delegate_declaration;
	VALA_CODE_VISITOR_CLASS (klass)->visit_delegate = vala_dova_delegate_module_real_visit_delegate;
}


static void vala_dova_delegate_module_instance_init (ValaDovaDelegateModule * self) {
}


/**
 * The link between a delegate and generated code.
 */
GType vala_dova_delegate_module_get_type (void) {
	static volatile gsize vala_dova_delegate_module_type_id__volatile = 0;
	if (g_once_init_enter (&vala_dova_delegate_module_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValaDovaDelegateModuleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_dova_delegate_module_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaDovaDelegateModule), 0, (GInstanceInitFunc) vala_dova_delegate_module_instance_init, NULL };
		GType vala_dova_delegate_module_type_id;
		vala_dova_delegate_module_type_id = g_type_register_static (VALA_TYPE_DOVA_VALUE_MODULE, "ValaDovaDelegateModule", &g_define_type_info, 0);
		g_once_init_leave (&vala_dova_delegate_module_type_id__volatile, vala_dova_delegate_module_type_id);
	}
	return vala_dova_delegate_module_type_id__volatile;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




