#!/bin/sh
#
# Copyright IBM, Corp. 2010
#
# Authors:
#  Anthony Liguori <aliguori@us.ibm.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.

# Set to the name of your bridge
BRIDGE=br0

# Turn off $BRIDGE
ifconfig $BRIDGE down

# Remove $BRIDGE
brctl delbr $BRIDGE

# Stopping dnsmasq
DNSMASQPID=`pgrep dnsmasq`
if [ ! "$DNSMASQPID" = "" ]; then
    kill $DNSMASQPID
fi

# Disable ip_forward
echo 0 | dd of=/proc/sys/net/ipv4/ip_forward > /dev/null

# Clean iptables rules
echo "Resetting iptables rules"
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
